#!/usr/bin/env python3
"""
PDF Summarizer Agent
Automatically summarizes PDF files using OpenAI API
"""

import os
import sys
import json
import glob
from pathlib import Path
from PyPDF2 import PdfReader
import openai
from github import Github
from datetime import datetime


def load_config():
    """Load configuration from config.json"""
    with open('config.json', 'r', encoding='utf-8') as f:
        return json.load(f)


def extract_text_from_pdf(pdf_path):
    """Extract text from a PDF file"""
    print(f"Extracting text from: {pdf_path}")
    text = ""
    try:
        with open(pdf_path, 'rb') as file:
            reader = PdfReader(file)
            num_pages = len(reader.pages)
            print(f"PDF has {num_pages} pages")
            
            for page_num in range(min(num_pages, 50)):  # Limit to first 50 pages
                page = reader.pages[page_num]
                text += page.extract_text() + "\n"
        
        return text
    except Exception as e:
        print(f"Error extracting PDF text: {e}")
        return ""


def summarize_with_openai(text, config):
    """Summarize text using OpenAI API"""
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        raise ValueError("OPENAI_API_KEY environment variable not set")
    
    openai.api_key = api_key
    
    # Truncate text if too long (OpenAI token limit)
    max_chars = 120000  # Approximately 30k tokens
    text = text[:max_chars]
    
    try:
        response = openai.ChatCompletion.create(
            model=config.get('model', 'gpt-4-turbo'),
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert document summarizer. Create comprehensive, clear summaries that capture the essential information."
                },
                {
                    "role": "user",
                    "content": f"Please summarize the following document in a clear, structured way with bullet points for key information:\n\n{text}"
                }
            ],
            max_tokens=2000,
            temperature=0.5
        )
        
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error with OpenAI API: {e}")
        raise


def save_summary(pdf_name, summary):
    """Save summary to a markdown file"""
    # Create summaries directory if it doesn't exist
    Path('summaries').mkdir(exist_ok=True)
    
    # Generate output filename
    base_name = os.path.splitext(pdf_name)[0]
    output_file = f"summaries/{base_name}_summary.md"
    
    # Create markdown content
    markdown_content = f"""# Summary: {base_name}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

{summary}

---
*This summary was automatically generated by PDF Summarizer Agent*
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    print(f"Summary saved to: {output_file}")
    return output_file


def commit_to_github(file_path, config):
    """Commit the summary file to GitHub"""
    try:
        github_token = os.getenv('GITHUB_TOKEN')
        if not github_token:
            print("Note: GITHUB_TOKEN not set, skipping auto-commit")
            return False
        
        g = Github(github_token)
        repo = g.get_user().get_repo(config.get('repo_name', 'pdf-summarizer-agent'))
        
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if file already exists
        try:
            existing_file = repo.get_contents(file_path)
            repo.update_file(
                file_path,
                f"Update summary: {os.path.basename(file_path)}",
                content,
                existing_file.sha
            )
            print(f"Updated file in repository: {file_path}")
        except:
            repo.create_file(
                file_path,
                f"Add summary: {os.path.basename(file_path)}",
                content
            )
            print(f"Created file in repository: {file_path}")
        
        return True
    except Exception as e:
        print(f"Error committing to GitHub: {e}")
        return False


def main():
    """Main function"""
    try:
        # Load configuration
        config = load_config()
        print("Configuration loaded successfully")
        
        # Find PDF files in current directory
        pdf_files = glob.glob('*.pdf')
        
        if not pdf_files:
            print("No PDF files found in current directory")
            return
        
        print(f"Found {len(pdf_files)} PDF file(s)")
        
        # Process each PDF
        for pdf_file in pdf_files:
            print(f"\n{'='*60}")
            print(f"Processing: {pdf_file}")
            print(f"{'='*60}")
            
            try:
                # Extract text from PDF
                text = extract_text_from_pdf(pdf_file)
                
                if not text.strip():
                    print("Warning: No text could be extracted from PDF")
                    continue
                
                print(f"Extracted {len(text)} characters")
                
                # Summarize with OpenAI
                print("Calling OpenAI API for summarization...")
                summary = summarize_with_openai(text, config)
                
                # Save summary
                output_file = save_summary(pdf_file, summary)
                
                # Commit to GitHub
                commit_to_github(output_file, config)
                
                print(f"✓ Successfully processed {pdf_file}")
                
            except Exception as e:
                print(f"✗ Error processing {pdf_file}: {e}")
                continue
        
        print(f"\n{'='*60}")
        print("All PDF files processed")
        print(f"{'='*60}")
        
    except Exception as e:
        print(f"Fatal error: {e}")
        sys.exit(2)


if __name__ == '__main__':
    main()
